package cn.cdjzxy.monitoringassistant.mvp.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cdjzxy.monitoringassistant.mvp.model.entity.project.Task;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK".
*/
public class TaskDao extends AbstractDao<Task, String> {

    public static final String TABLENAME = "TASK";

    /**
     * Properties of entity Task.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "Id", true, "ID");
        public final static Property UpdateTime = new Property(1, String.class, "UpdateTime", false, "UPDATE_TIME");
        public final static Property Name = new Property(2, String.class, "Name", false, "NAME");
        public final static Property ProjectNo = new Property(3, String.class, "ProjectNo", false, "PROJECT_NO");
        public final static Property Urgency = new Property(4, String.class, "Urgency", false, "URGENCY");
        public final static Property ContractCode = new Property(5, String.class, "ContractCode", false, "CONTRACT_CODE");
        public final static Property Type = new Property(6, String.class, "Type", false, "TYPE");
        public final static Property MonType = new Property(7, String.class, "MonType", false, "MON_TYPE");
        public final static Property ClientName = new Property(8, String.class, "ClientName", false, "CLIENT_NAME");
        public final static Property ClientId = new Property(9, String.class, "ClientId", false, "CLIENT_ID");
        public final static Property CreaterId = new Property(10, String.class, "CreaterId", false, "CREATER_ID");
        public final static Property CreaterName = new Property(11, String.class, "CreaterName", false, "CREATER_NAME");
        public final static Property RcvId = new Property(12, String.class, "RcvId", false, "RCV_ID");
        public final static Property RcvName = new Property(13, String.class, "RcvName", false, "RCV_NAME");
        public final static Property StartDate = new Property(14, String.class, "StartDate", false, "START_DATE");
        public final static Property EndDate = new Property(15, String.class, "EndDate", false, "END_DATE");
        public final static Property CurrentNodeType = new Property(16, String.class, "CurrentNodeType", false, "CURRENT_NODE_TYPE");
        public final static Property Status = new Property(17, String.class, "Status", false, "STATUS");
        public final static Property AssignDate = new Property(18, String.class, "AssignDate", false, "ASSIGN_DATE");
        public final static Property CreateDate = new Property(19, String.class, "CreateDate", false, "CREATE_DATE");
        public final static Property FinishState = new Property(20, boolean.class, "FinishState", false, "FINISH_STATE");
        public final static Property FinishDate = new Property(21, String.class, "FinishDate", false, "FINISH_DATE");
    }


    public TaskDao(DaoConfig config) {
        super(config);
    }
    
    public TaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: Id
                "\"UPDATE_TIME\" TEXT," + // 1: UpdateTime
                "\"NAME\" TEXT," + // 2: Name
                "\"PROJECT_NO\" TEXT," + // 3: ProjectNo
                "\"URGENCY\" TEXT," + // 4: Urgency
                "\"CONTRACT_CODE\" TEXT," + // 5: ContractCode
                "\"TYPE\" TEXT," + // 6: Type
                "\"MON_TYPE\" TEXT," + // 7: MonType
                "\"CLIENT_NAME\" TEXT," + // 8: ClientName
                "\"CLIENT_ID\" TEXT," + // 9: ClientId
                "\"CREATER_ID\" TEXT," + // 10: CreaterId
                "\"CREATER_NAME\" TEXT," + // 11: CreaterName
                "\"RCV_ID\" TEXT," + // 12: RcvId
                "\"RCV_NAME\" TEXT," + // 13: RcvName
                "\"START_DATE\" TEXT," + // 14: StartDate
                "\"END_DATE\" TEXT," + // 15: EndDate
                "\"CURRENT_NODE_TYPE\" TEXT," + // 16: CurrentNodeType
                "\"STATUS\" TEXT," + // 17: Status
                "\"ASSIGN_DATE\" TEXT," + // 18: AssignDate
                "\"CREATE_DATE\" TEXT," + // 19: CreateDate
                "\"FINISH_STATE\" INTEGER NOT NULL ," + // 20: FinishState
                "\"FINISH_DATE\" TEXT);"); // 21: FinishDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Task entity) {
        stmt.clearBindings();
 
        String Id = entity.getId();
        if (Id != null) {
            stmt.bindString(1, Id);
        }
 
        String UpdateTime = entity.getUpdateTime();
        if (UpdateTime != null) {
            stmt.bindString(2, UpdateTime);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        String ProjectNo = entity.getProjectNo();
        if (ProjectNo != null) {
            stmt.bindString(4, ProjectNo);
        }
 
        String Urgency = entity.getUrgency();
        if (Urgency != null) {
            stmt.bindString(5, Urgency);
        }
 
        String ContractCode = entity.getContractCode();
        if (ContractCode != null) {
            stmt.bindString(6, ContractCode);
        }
 
        String Type = entity.getType();
        if (Type != null) {
            stmt.bindString(7, Type);
        }
 
        String MonType = entity.getMonType();
        if (MonType != null) {
            stmt.bindString(8, MonType);
        }
 
        String ClientName = entity.getClientName();
        if (ClientName != null) {
            stmt.bindString(9, ClientName);
        }
 
        String ClientId = entity.getClientId();
        if (ClientId != null) {
            stmt.bindString(10, ClientId);
        }
 
        String CreaterId = entity.getCreaterId();
        if (CreaterId != null) {
            stmt.bindString(11, CreaterId);
        }
 
        String CreaterName = entity.getCreaterName();
        if (CreaterName != null) {
            stmt.bindString(12, CreaterName);
        }
 
        String RcvId = entity.getRcvId();
        if (RcvId != null) {
            stmt.bindString(13, RcvId);
        }
 
        String RcvName = entity.getRcvName();
        if (RcvName != null) {
            stmt.bindString(14, RcvName);
        }
 
        String StartDate = entity.getStartDate();
        if (StartDate != null) {
            stmt.bindString(15, StartDate);
        }
 
        String EndDate = entity.getEndDate();
        if (EndDate != null) {
            stmt.bindString(16, EndDate);
        }
 
        String CurrentNodeType = entity.getCurrentNodeType();
        if (CurrentNodeType != null) {
            stmt.bindString(17, CurrentNodeType);
        }
 
        String Status = entity.getStatus();
        if (Status != null) {
            stmt.bindString(18, Status);
        }
 
        String AssignDate = entity.getAssignDate();
        if (AssignDate != null) {
            stmt.bindString(19, AssignDate);
        }
 
        String CreateDate = entity.getCreateDate();
        if (CreateDate != null) {
            stmt.bindString(20, CreateDate);
        }
        stmt.bindLong(21, entity.getFinishState() ? 1L: 0L);
 
        String FinishDate = entity.getFinishDate();
        if (FinishDate != null) {
            stmt.bindString(22, FinishDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Task entity) {
        stmt.clearBindings();
 
        String Id = entity.getId();
        if (Id != null) {
            stmt.bindString(1, Id);
        }
 
        String UpdateTime = entity.getUpdateTime();
        if (UpdateTime != null) {
            stmt.bindString(2, UpdateTime);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        String ProjectNo = entity.getProjectNo();
        if (ProjectNo != null) {
            stmt.bindString(4, ProjectNo);
        }
 
        String Urgency = entity.getUrgency();
        if (Urgency != null) {
            stmt.bindString(5, Urgency);
        }
 
        String ContractCode = entity.getContractCode();
        if (ContractCode != null) {
            stmt.bindString(6, ContractCode);
        }
 
        String Type = entity.getType();
        if (Type != null) {
            stmt.bindString(7, Type);
        }
 
        String MonType = entity.getMonType();
        if (MonType != null) {
            stmt.bindString(8, MonType);
        }
 
        String ClientName = entity.getClientName();
        if (ClientName != null) {
            stmt.bindString(9, ClientName);
        }
 
        String ClientId = entity.getClientId();
        if (ClientId != null) {
            stmt.bindString(10, ClientId);
        }
 
        String CreaterId = entity.getCreaterId();
        if (CreaterId != null) {
            stmt.bindString(11, CreaterId);
        }
 
        String CreaterName = entity.getCreaterName();
        if (CreaterName != null) {
            stmt.bindString(12, CreaterName);
        }
 
        String RcvId = entity.getRcvId();
        if (RcvId != null) {
            stmt.bindString(13, RcvId);
        }
 
        String RcvName = entity.getRcvName();
        if (RcvName != null) {
            stmt.bindString(14, RcvName);
        }
 
        String StartDate = entity.getStartDate();
        if (StartDate != null) {
            stmt.bindString(15, StartDate);
        }
 
        String EndDate = entity.getEndDate();
        if (EndDate != null) {
            stmt.bindString(16, EndDate);
        }
 
        String CurrentNodeType = entity.getCurrentNodeType();
        if (CurrentNodeType != null) {
            stmt.bindString(17, CurrentNodeType);
        }
 
        String Status = entity.getStatus();
        if (Status != null) {
            stmt.bindString(18, Status);
        }
 
        String AssignDate = entity.getAssignDate();
        if (AssignDate != null) {
            stmt.bindString(19, AssignDate);
        }
 
        String CreateDate = entity.getCreateDate();
        if (CreateDate != null) {
            stmt.bindString(20, CreateDate);
        }
        stmt.bindLong(21, entity.getFinishState() ? 1L: 0L);
 
        String FinishDate = entity.getFinishDate();
        if (FinishDate != null) {
            stmt.bindString(22, FinishDate);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Task readEntity(Cursor cursor, int offset) {
        Task entity = new Task( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UpdateTime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ProjectNo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Urgency
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ContractCode
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Type
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // MonType
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ClientName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ClientId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // CreaterId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // CreaterName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // RcvId
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // RcvName
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // StartDate
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // EndDate
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // CurrentNodeType
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // Status
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // AssignDate
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // CreateDate
            cursor.getShort(offset + 20) != 0, // FinishState
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21) // FinishDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Task entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUpdateTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProjectNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrgency(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setContractCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMonType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setClientName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setClientId(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCreaterId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCreaterName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRcvId(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRcvName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setStartDate(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setEndDate(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCurrentNodeType(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setStatus(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setAssignDate(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setCreateDate(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setFinishState(cursor.getShort(offset + 20) != 0);
        entity.setFinishDate(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Task entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Task entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Task entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
